version: "3"

services:
  google-cloud-mysqldumper:
    build:
      context: .
      dockerfile: dockerfile
    working_dir: /usr/src/service
    command: npm install
    volumes:
      - ./:/usr/src/service
